name: Generate Snake Animation

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Generar Animación
        uses: Platane/snk@v2
        with:
          github_user_name: Fabricioz01
          outputs: dist/snake.svg

      - name: Subir Animación
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg

  deploy:
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
